// Import the correct Router from Next.js
'use client'
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
// import logo from "@/assets/images/Logo.png";
// import Image from "next/image";
// import SearchComponent from "@/components/Search";
// import { useEffect } from "react";
// import { useRouter } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
//   const router = useRouter()

// useEffect(()=>{
//   const token = localStorage.getItem('cookieFallback')
//   console.log(token)
//   if(!token){
//     router.push('/login')
//     return
//   }else{
//     router.push('/home')
//   }
  
// },[])




  return (
    <html lang="en">
      <body >
        {children}
        
      </body>
    </html>
  );
};

export default RootLayout;
