// Import the correct Router from Next.js
'use client'
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import logo from "@/assets/images/Logo.png";
import Image from "next/image";
import SearchComponent from "@/components/Search";
import { useEffect } from "react";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const router = useRouter()

useEffect(()=>{
  const token = localStorage.getItem('cookieFallback')
  console.log(token)
  if(!token){
    router.push('/login')
    return
  }else{
    router.push('/home')
  }
  
},[])




  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <nav className="bg-white p-4 sticky top-0 z-10">
            <div className="container mx-auto flex items-center justify-between">
              <a className="navbar-brand " href="#">
                <Image src={logo} alt="" className="w-16 h-9" />
              </a>
              <div className="flex items-center relative">
                {/* <SearchComponent /> */}
                <button
                  className=" focus:outline-none ml-8"
                  type="button"
                  aria-label="Toggle navigation"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="27"
                    height="25"
                    viewBox="0 0 27 25"
                    fill="black"
                  >
                    <path d="M0 2H27" stroke="black" strokeWidth="4" />
                    <path d="M0 12.0166H27" stroke="black" strokeWidth="4" />
                    <path d="M0 22.0322H27" stroke="black" strokeWidth="4" />
                  </svg>
                </button>
              </div>
            </div>
          </nav>
        </>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
};

export default RootLayout;
